# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Style/StringLiterals:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Rails:
  TargetRailsVersion: 8.0

AllCops:
  TargetRubyVersion: 3.4
